apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: cluster-namespaced-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: example.com/v1
    resource: cluster-namespaceds
  childResources:
  - apiVersion: networking.k8s.io/v1
    resource: networkpolicies
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://cluster-namespaced-controller.cluster-namespaced/sync