apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cluster-namespaceds.example.com
spec:
  group: example.com
  version: v1
  names:
    kind: ClusterNamespaced
    plural: cluster-namespaceds
    singular: cluster-namespaced
  scope: Cluster